@Server_HostAddress = http://localhost:5242

# пецхярпюжхъ
POST {{Server_HostAddress}}/auth/register
Content-Type: application/json
{
    "email": "mytest@test.com",
    "password": "Test123!",
    "confirmPassword": "Test123!",
    "fullName": "Tester"
}

###

# кнцхм
POST {{Server_HostAddress}}/auth/login
Content-Type: application/json
{
    "email": "test@test.com",
    "password": "Test123!"
    
}

###

# кнцюср
POST {{Server_HostAddress}}/auth/logout
Content-Type: application/json
{
    "email": "test@test.com",
    "password": "Test123!"
}

###



# яохянй рнбюпнб
GET {{Server_HostAddress}}/store/all
Content-Type: application/json
{
}

###

# яохянй рнбюпнб (тск хмтю)
GET {{Server_HostAddress}}/store/all_full
Content-Type: application/json
{
}

###

# тск хмтю н рнбюпе
GET {{Server_HostAddress}}/store/full_info/6
Content-Type: application/json
{
}

###



# днаюбкемхе б йнпгхмс
POST {{Server_HostAddress}}/cart/add
Content-Type: application/json
{
    "userId": "25cace0c-c50c-4316-b140-92df2833b99b",
    "productId": 12
    
}

###

# онксвемхе йнпгхмш онкэгнбюрекъ
GET {{Server_HostAddress}}/cart/user_cart/25cace0c-c50c-4316-b140-92df2833b99b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNWE1OWJkZi0yY2RiLTQyYTItYjhhMy1iZmJmMTg3MjliNDMiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJqdGkiOiI1Y2Q0Y2Y3ZS03Nzc5LTQwMTctYWMwZi0yNTM4MTFhNjMwOGMiLCJleHAiOjE3NDIyMDU4MjYsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.7zWWCB4LYA9wQ6dzlbeo0joNQ917U8XL1Ujy0cb_QSI
Content-Type: application/json
{
}

###



# нтнплкемхе гюйюгю
GET {{Server_HostAddress}}/order/create/25cace0c-c50c-4316-b140-92df2833b99b
Content-Type: application/json
{
}

###

# яохянй бяеу гюйюгнб онкэгнбюрекъ
GET {{Server_HostAddress}}/order/all/25cace0c-c50c-4316-b140-92df2833b99b
Content-Type: application/json
{
}

###

#  тскк хмтю н гюйюге
GET {{Server_HostAddress}}/order/info/1
Content-Type: application/json
{
}

###

#  яохянй гюйюгнб бшанпйю он ярюрсяс
GET {{Server_HostAddress}}/order/all_by_status/Pending
Content-Type: application/json
{
}

###

# хглемемхе ярюрсяю гюйюгю
POST {{Server_HostAddress}}/order/edit/1/Processing
Content-Type: application/json
{
    "userId": "25cace0c-c50c-4316-b140-92df2833b99b",
    "productId": 12
    
}

###

# хглемемхе ярюрсяю гюйюгю
DELETE {{Server_HostAddress}}/order/remove_order_item/9
Content-Type: application/json
{  
}

###