@Server_HostAddress = http://localhost:5242


POST {{Server_HostAddress}}/auth/register
Content-Type: application/json
{
    "email": "test@test.com",
    "password": "Test123!"
}

###

POST {{Server_HostAddress}}/auth/login
Content-Type: application/json
{
    "email": "test@test.com",
    "password": "Test123!"
}

###

POST {{Server_HostAddress}}/auth/logout
Content-Type: application/json
{
    "email": "test@test.com",
    "password": "Test123!"
}

###